<template>
	<div class="flex flex-col gap-8 ">
		<MainTitle
			class="bg-clip-text bg-gradient-to-r from-sky-600 via-teal-400 to-yellow-500 text-transparent text-focus-in ">
		Front End Developer , self learner,   <span class="typewritter"></span>
		</MainTitle>

		<MainParagraph>
			Hello, i am <span class="text-sky-500">Zackaria Slimane</span> , a passionate
			<span class="text-yellow-500">javascript</span>	front end developer
			With experience in <span class="text-green-600">Vue JS</span> .
		</MainParagraph>

		<MainParagraph>
			I'm currently working full-time for
			<LinkBtn class="text-rose-500" link="http://adhocmaroc.com" text="ADHOC Agency" />
			a digital marketing agency.  While also moving to
			<LinkBtn class="!text-blue-500" link="https://reactjs.org" text="React" />
		</MainParagraph>
	</div>
</template>

<style>
.text-focus-in {
	-webkit-animation: text-focus-in 1s cubic-bezier(0.550, 0.085, 0.680, 0.530) both;
	        animation: text-focus-in 1s cubic-bezier(0.550, 0.085, 0.680, 0.530) both;
}
/* ----------------------------------------------
 * Generated by Animista on 2023-3-7 21:24:16
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */


@-webkit-keyframes text-focus-in {
  0% {
    -webkit-filter: blur(12px);
            filter: blur(12px);
    opacity: 0;
  }
  100% {
    -webkit-filter: blur(0px);
            filter: blur(0px);
    opacity: 1;
  }
}
@keyframes text-focus-in {
  0% {
    -webkit-filter: blur(12px);
            filter: blur(12px);
    opacity: 0;
  }
  100% {
    -webkit-filter: blur(0px);
            filter: blur(0px);
    opacity: 1;
  }
}

</style>

<script setup>
import { onMounted } from 'vue';

onMounted(()=>{
	let nouns = [ "javaScript Passionate", "Wordpress & Shopify enthusiast"];
	let noun = nouns[0];
	let nounIndex = 0;
	const typewritterText = document.querySelector(".typewritter")
	if (typewritterText){
		typewritterText.textContent = noun
		setInterval(() => {
			nounIndex = (nounIndex + 1) % nouns.length
			noun = nouns[nounIndex]
			typewritterText.textContent= noun
		}, 5000);
	}
})
</script>